name: Publish Package to PyPI 

on:
  push:
    branches: [main]

  release:

    types: [created]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install  numpy filetype setuptools wheel twine
    - name: Build Source and Wheel Distributions
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish Distribution to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*




